# Generated by Django 2.0.1 on 2018-01-09 12:10

from django.db import migrations, models
import django.db.models.deletion
import heroku_connect.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sf_id', heroku_connect.db.models.fields.ID(db_column='sfid', db_index=True, editable=False, max_length=18, sf_field_name='ID', unique=True, upsert=False)),
                ('system_mod_stamp', heroku_connect.db.models.fields.DateTime(db_column='systemmodstamp', db_index=True, null=True, sf_field_name='SystemModstamp', upsert=False)),
                ('_hc_lastop', models.CharField(editable=False, help_text='Indicates the last sync operation Heroku Connect performed on the record', max_length=32)),
                ('_hc_err', models.TextField(editable=False, help_text='If the last sync operation by Heroku Connect resulted in an error then this column will contain a JSON object containing more information about the error', max_length=1024)),
                ('username', heroku_connect.db.models.fields.Text(db_column='username', max_length=80, null=True, sf_field_name='Username', upsert=False)),
                ('email', heroku_connect.db.models.fields.Email(db_column='email', max_length=80, null=True, sf_field_name='Email', upsert=False)),
                ('department', heroku_connect.db.models.fields.Text(db_column='department', max_length=80, null=True, sf_field_name='Department', upsert=False)),
                ('title', heroku_connect.db.models.fields.Text(db_column='title', max_length=80, null=True, sf_field_name='Title', upsert=False)),
            ],
            options={
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='salesforce.User', to_field='sf_id')),
            ],
        ),
    ]
